#!/usr/bin/env python3
import argparse
import json
from datetime import datetime
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert extracted XiaoMan records into miniapp-compatible Log[] JSON."
    )
    parser.add_argument(
        "--input",
        default="data/extracted/xiaoman_records.ndjson",
        help="Input NDJSON path generated by extract_xiaoman_records.py",
    )
    parser.add_argument(
        "--output",
        default="data/moments_logs.json",
        help="Output JSON file path",
    )
    parser.add_argument(
        "--merge-with",
        action="append",
        default=[],
        help="Optional existing logs.json path(s) to merge with. Repeatable.",
    )
    return parser.parse_args()


def ts_to_ms(value: str) -> int:
    return int(datetime.strptime(value, "%Y-%m-%d %H:%M:%S").timestamp() * 1000)


def load_ndjson(path: Path) -> list[dict]:
    if not path.exists():
        return []
    rows: list[dict] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        rows.append(json.loads(line))
    return rows


def convert_row(row: dict, idx: int) -> dict:
    happened_at = row["happened_at"]
    timestamp = ts_to_ms(happened_at)
    return {
        "id": f"ai-{timestamp}-{idx}",
        "type": row["aligned_log_type"],
        "amount": row["aligned_amount"],
        "description": row["aligned_description"],
        "timestamp": timestamp,
        "source": "xiaogpt-local",
        "rawQuery": row.get("query", ""),
        "matchedKeyword": row.get("matched_keyword", ""),
        "alignedTaskTitle": row.get("aligned_task_title"),
    }


def dedupe_logs(logs: list[dict]) -> list[dict]:
    seen: set[tuple] = set()
    result: list[dict] = []
    for log in sorted(logs, key=lambda x: x["timestamp"], reverse=True):
        key = (
            log.get("type"),
            log.get("description"),
            log.get("timestamp"),
            log.get("amount"),
        )
        if key in seen:
            continue
        seen.add(key)
        result.append(log)
    return result


def main() -> None:
    args = parse_args()
    input_path = Path(args.input)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    rows = load_ndjson(input_path)
    converted = [convert_row(row, idx) for idx, row in enumerate(rows, start=1)]

    merged = converted
    for merge_input in args.merge_with:
        merge_path = Path(merge_input)
        if merge_path.exists():
            existing = json.loads(merge_path.read_text(encoding="utf-8"))
            if isinstance(existing, list):
                merged = dedupe_logs(converted + existing)
                converted = merged

    output_path.write_text(
        json.dumps(merged, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    print(f"input_records={len(rows)}")
    print(f"output_logs={len(merged)}")
    print(f"output={output_path}")


if __name__ == "__main__":
    main()
